"""
Feed gen settings
"""

import os


FEEDGEN_HOSTNAME = os.getenv("FEEDGEN_HOSTNAME", "feed.flatlander.social")
FEEDGEN_SERVICE_DID = os.getenv("FEEDGEN_SERVICE_DID", f"did:web:{FEEDGEN_HOSTNAME}")
FEEDGEN_LISTENHOST = os.getenv("FEEDGEN_LISTENHOST", "localhost")
FEEDGEN_SUBSCRIPTION_ENDPOINT = os.getenv(
    "FEEDGEN_SUBSCRIPTION_ENDPOINT", "wss://bsky.social"
)
FEEDGEN_SERVICE_DID = f"did:web:{FEEDGEN_HOSTNAME}"
FEEDGEN_DB_URL = os.getenv("FEEDGEN_DB_URL")
FEEDGEN_DB_TYPE = os.getenv("FEEDGEN_DB_TYPE", "sqlite")
FEEDGEN_DB_HOST = os.getenv("FEEDGEN_DB_HOST", "localhost")
FEEDGEN_DB_PORT = int(os.getenv("FEEDGEN_DB_PORT", "5432"))
FEEDGEN_DB_USERNAME = os.getenv("FEEDGEN_DB_USERNAME", "postgres")
FEEDGEN_DB_PASSWORD = os.getenv("FEEDGEN_DB_PASSWORD", "postgres")
FEEDGEN_DB_NAME = os.getenv("FEEDGEN_DB_NAME", "feedgen")
FEEDGEN_DB_SSL_CERT = os.getenv("FEEDGEN_DB_SSL_CERT", "")
FEEDGEN_ADMIN_DID = os.getenv("FEEDGEN_ADMIN_DID", "did:plc:cug2evrqa3nhdbvlfd2cvtky")
FEEDGEN_PUBLISHER_DID = os.getenv("FEEDGEN_PUBLISHER_DID", "")
FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY = int(
    os.getenv("FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY", "1000")
)
FEEDGEN_POST_THRESHOLD = int(os.getenv("FEEDGEN_POST_THRESHOLD", "2"))

PUBLISHER_HANDLE = os.getenv("PUBLISHER_HANDLE", "")
PUBLISHER_APP_PASSWORD = os.getenv("PUBLISHER_APP_PASSWORD", "")
RECORD_NAME = os.getenv("RECORD_NAME", "")
DISPLAY_NAME = os.getenv("DISPLAY_NAME", "")
DESCRIPTION = os.getenv("DESCRIPTION", "")
AVATAR_PATH = os.getenv("AVATAR_PATH", "")
