# Generated by Django 4.2.5 on 2023-09-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("cid", models.CharField(max_length=255, null=True)),
                (
                    "uri",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("subject", models.TextField()),
                ("author", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegisteredUser",
            fields=[
                (
                    "did",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("indexed_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "uri",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("cid", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("reply_parent", models.CharField(max_length=255, null=True)),
                ("reply_root", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(null=True)),
                ("indexed_at", models.DateTimeField(auto_now_add=True)),
                ("reposts", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("is_community_match", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="flatlanders.registereduser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
