# Generated by Django 4.2.5 on 2023-09-14 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("flatlanders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
