# Generated by Django 5.0.6 on 2024-05-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flatlanders", "0002_alter_registereduser_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="labelerCursorState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("labeler_service", models.CharField(max_length=255, unique=True)),
                ("cursor", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
