# Generated by Django 5.1.3 on 2024-11-19 19:00
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("flatlanders", "0003_labellercursorstate"),
    ]
    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="flatlanders.registereduser",
            ),
        ),
    ]
