# Generated by Django 5.1.3 on 2024-11-19 19:00
import django.db.models.deletion
from django.db import migrations, models


def clear_add_author_dids(apps, schema_editor):
    """Delete all users that are not registered"""
    Post = apps.get_model("flatlanders", "Post")
    for post in Post.objects.filter(author__isnull=False):
        post.author_did = post.author.did
        post.save()


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("flatlanders", "0003_labellercursorstate"),
    ]
    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="flatlanders.registereduser",
            ),
        ),
        migrations.RemoveField(
            model_name="registereduser",
            name="expires_at",
        ),
        migrations.AddField(
            model_name="post",
            name="author_did",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(clear_add_author_dids),
    ]
