# Generated by Django 5.1.3 on 2024-11-19 19:00
from django.db import migrations


def remove_unregistered_users(apps, schema_editor):
    """Delete all users that are not registered"""
    RegisteredUser = apps.get_model("flatlanders", "RegisteredUser")
    RegisteredUser.objects.exclude(expires_at__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("flatlanders", "0004_post_foriegn_key"),
    ]
    operations = [  # noqa: RUF012
        migrations.RunPython(remove_unregistered_users),
    ]
