# Generated by Django 5.1.3 on 2024-11-19 19:00
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("flatlanders", "0005_remove_registeredusers"),
    ]
    operations = [  # noqa: RUF012
        migrations.RemoveField(
            model_name="registereduser",
            name="expires_at",
        ),
        migrations.AddField(
            model_name="post",
            name="author_did",
            field=models.CharField(max_length=255, null=True),
        )
    ]
