# Generated by Django 5.1.3 on 2024-11-19 19:00
from django.db import migrations, models


def clear_add_author_dids(apps, schema_editor):
    """Delete all users that are not registered"""
    Post = apps.get_model("flatlanders", "Post")
    Post.objects.filter(author__isnull=False).update(author_did=models.F("author__did"))


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("flatlanders", "0007_alter_post_text"),
    ]
    operations = [  # noqa: RUF012
        migrations.RunPython(clear_add_author_dids),
    ]
