# Generated by Django 5.1.3 on 2024-11-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firehose', '0002_alter_subscriptionstate_cursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionstate',
            name='cursor',
            field=models.FloatField(default=0.0),
        ),
    ]
